name: Test LocalGov Drupal

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - name: Clone drupal_container
        uses: actions/checkout@v2
        with:
          repository: localgovdrupal/drupal-container
          ref: master

      - name: Checkout ${{ github.event.repository.name }} branch to test
        uses: actions/checkout@v2
        with:
          path: html/web/modules/contrib/${{ github.event.repository.name }}

      - name: Start Docker environment
        run: docker-compose up -d

      - name: Create LocalGov Drupal project
        run: |
          docker exec -u root -t drupal bash -c "mkdir -p /var/www/html && chown docker:docker /var/www/html"
          docker exec -u docker -t drupal bash -c "/usr/local/bin/composer create-project --keep-vcs --stability dev localgovdrupal/localgov-project /var/www/html"

      - name: Run tests
        run: ./run-tests.sh
        shell: bash
